### ISSUE TITLE
Fix the jest unit tests

### ISSUE THREAD

**Issue by wandyezj** [visual-studio-code-extensions/visual-studio-code-extension-project#2]
expect.objectContaining(object)
https://jestjs.io/docs/expect#expectobjectcontainingobject
           name: "x",
            text: "const x = 2 + 5 + 2",
            variableType: "const",
            value: 9,

**Comment by Majd223** [comment]
In Samples folder we have a file named "test.ts" and Jest is running that thinking its a unite test but actually its just a playground.
